# local_backend: true

backend:
  name: github
  repo: martpie/elzara
  branch: master
  base_url: https://sveltia-cms-auth.martpie.workers.dev

media_folder: public/uploads
public_folder: /uploads

media_libraries:
  default:
    config:
      transformations:
        raster_image:
          format: webp
          quality: 90
          width: 1920
          height: 1920
        svg:
          optimize: true

collections:
  - name: project
    label: Project
    icon: event_note
    folder: content/projects
    create: true
    slug: "{{slug}}"
    editor:
      preview: false

    fields:
      - label: Title
        name: title
        widget: string

      - label: Featured Image
        name: thumbnail
        widget: image
        hint: This image will be used as the main image on the homepage and detail pages.

      - label: Publish Date
        name: publish_date
        widget: datetime
        format: YYYY-MM-DD
        dateFormat: YYYY-MM-DD
        timeFormat: false
        hint: Used for the sorting of the projects on the homepage.

      - label: Project Date
        name: project_date
        widget: string
        hint: Human readable date indicating when the project took place.

      - label: Description
        name: description
        widget: string
        hint: Short summary of the project, used on the homepage.

      - label: Highlight
        name: highlight
        widget: string
        required: false
        hint: Optional pink message to highlight important

      - label: Body
        name: body
        widget: markdown

  - name: "settings"
    label: "Settings"
    icon: "settings"
    delete: false # Prevents accidental deletion
    editor:
      preview: false
    files:
      - file: "content/settings.json"
        label: "Site Settings"
        name: "site_settings"
        fields:
          - label: Portfolio
            name: portfolio
            widget: file
            allow_multiple: false
            hint: Link to the latest portfolio

show_preview_links: false
